/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./Raidexi/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: "#f2a60d",
        "background-light": "#f8f7f5",
        "background-dark": "#1a1612",
        "surface-dark": "#262018",
        "paper-white": "#e6e1d6",
        "panel-bg": "#221c15",
        "panel-header": "#262018",
        "input-bg": "#1a1612",
        "text-main": "#e0dcd5",
        "text-dim": "#bab09c",
        "text-dark": "#181611",
        "border-subtle": "#383429",
        "border-brass": "#544c3b",
        "accent-brass": "#f2a60d",
        "decor-dark": "#3a3429",
        "surface-dark": "#231e18",
        "surface-hover": "#2a241d",
        "text-aged": "#e6e1d3",
        "text-muted": "#9c9486",
        "border-brass": "#5c4f3a",
        "terminal-black": "#13100c",
        "border-dark": "#544d3b",
        "surface-dark": "#2a2415",
        "border-color": "#393328",
        "border-highlight": "#544b3b",
        "text-main": "#f2f0ed",
        "text-muted": "#b9af9d",
      },
      fontFamily: {
        display: ["Newsreader", "serif"],
        mono: ["JetBrains Mono", "monospace"],
        sans: ["Noto Sans", "sans-serif"],
        display: ["Newsreader", "serif"],
        sans: ["Noto Sans", "sans-serif"],
        mono: [
          "ui-monospace",
          "SFMono-Regular",
          "Menlo",
          "Monaco",
          "Consolas",
          "Liberation Mono",
          "Courier New",
          "monospace",
        ],
      },
      borderRadius: {
        DEFAULT: "0px",
        sm: "0px",
        lg: "0px",
        xl: "0px",
        full: "0px",
        none: "0px",
      },
      animation: {
        "pulse-fast": "pulse 1s cubic-bezier(0.4, 0, 0.6, 1) infinite",
        marquee: "marquee 25s linear infinite",
        pulse: "pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite",
      },
      keyframes: {
        marquee: {
          "0%": { transform: "translateX(0%)" },
          "100%": { transform: "translateX(-100%)" },
        },
      },
    },
  },
  plugins: [],
};
